kind: Rules
metadata:
  namespace: k8s-tutorial
spec:
  - name: k8s.ImageTag
    description: "Replace image tag after CI produces new image"
    condition:
      deployedType: k8s.Resources
      expression: "#input.getStringValue('$.kind') == 'Deployment'"
    processor:
      - type: patch
        description: "Changing image tag"
        phase: PATCH
        merge:
          type: overlay
        parameters:
          patch:
            - op: replace
              path: "/spec/template/spec/containers/0/image"
              value: "#{'{{image_name}}:'+#ctx.getCurrentDeployedApplication().getName()}"